# Generated by Django 5.2.6 on 2025-10-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_owner_product_status"),
    ]

    operations = []
